#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # selected=$(find ~/work/builds ~/projects ~/ ~/work ~/personal ~/personal/yt ~/personal/ub -mindepth 1 -maxdepth 1 -type d | fzf)
    selected=$(
	# get my project's namespaces
	# I have it organized in namespaces per organization, so I have
	# my personal org (caarlos0), one for work, one for goreleaser, and so on.
	find ~/Documents ~/Documents/personal/ub ~/.config -type d -maxdepth 1 |
	while read -r p; do
		# get the projects in each namespace with their zoxide scores
		zoxide query -l -s "$p/";
	done |
	sort -rnk1 |     # sort by zoxide score (first column)
	fzf --no-sort |  # pipe to fzf without its sorting
	awk '{print $2}' # use the path as selected (second column)
)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
